services:
  node:
    container_name: node
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /app
    ports:
      - 8000:$PORT
    command: npm run dev
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:$MONGO_PORT
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASS