version: '3'
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /app
    ports:
      - 3000:3000
    command: npm run dev